name: CI
on:
 push:
   branches: [ main, develop, ci-pipeline-poc ]
 pull_request:
   branches: [ main, develop ]
jobs:
 build-test:
   runs-on: ubuntu-latest
   steps:
      - name: Access Repository Variable
        run: echo "Repository Variable Value ${{ vars.MS_NAME }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
     # 🔧 Normaliza EOL a LF y asegura permisos
      - name: Prepare gradlew
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          ls -l gradlew
          head -n1 gradlew
     # 🚀 Ejecuta con bash (evita problemas de permisos)
      - name: Build & Test
        run: bash ./gradlew clean build --no-daemon
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/test/*
            **/build/reports/tests/test/*
          if-no-files-found: ignore
      - name: Upload app artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jars
          path: |
            **/build/libs/*.jar