name: Dependency Install
on:
 workflow_call:        # habilita que lo llamen otros repos
jobs:
  dependency:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
      - name: Build  
        run: npm ci
      - name: Unit Test
        run: npm test