name: Registry Harbor
on:
 workflow_call:        # habilita que lo llamen otros repos
jobs:
  Harbor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ github.ref_name}}
    if: ${{ github.ref_name != 'develop' }}
    steps:
      - name: Access Repository Secrets Variable
        run: echo "Configuracion Harbor Registry"